# -*- coding: utf-8 -*-
"""Pixelmind Backend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XWV40qm0jMe7Xos1-GnyRSGvqUCZd7Vg
"""

!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
!pip install diffusers transformers accelerate safetensors flask flask-cors

from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
from diffusers import StableDiffusionPipeline
import torch
from PIL import Image
from io import BytesIO
import os

!pip install -U diffusers==0.30.0 transformers==4.44.0 accelerate==0.33.0 safetensors==0.4.3

from diffusers import StableDiffusionPipeline
import torch

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

print("Loading base Stable Diffusion model...")
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
).to(DEVICE)

print(" Model loaded successfully!")

app = Flask(__name__)
CORS(app)
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

print("Loading base Stable Diffusion model...")
base_model_id = "runwayml/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(
    base_model_id, torch_dtype=torch.float16
)
pipe.to(DEVICE)

LORA_PATHS = {
    "anime": "/content/anime_lora.safetensors",
    "realistic": "/content/realistic_lora.safetensors"
}

def apply_lora(pipe, lora_path, alpha=0.75):
    import safetensors.torch
    weights = safetensors.torch.load_file(lora_path)
    for key in weights:
        if key in pipe.unet.state_dict():
            pipe.unet.state_dict()[key] += alpha * weights[key]

@app.route("/generate", methods=["POST"])
def generate_image():
    data = request.get_json()
    prompt = data.get("prompt", "")
    style = data.get("style", "realistic")

    if os.path.exists(LORA_PATHS[style]):
        apply_lora(pipe, LORA_PATHS[style])
        print(f"Applied {style} LoRA")

    with torch.autocast("cuda"):
        image = pipe(prompt, num_inference_steps=30, guidance_scale=7.5).images[0]

    buffer = BytesIO()
    image.save(buffer, format="PNG")
    buffer.seek(0)
    return send_file(buffer, mimetype="image/png")

!pip install pyngrok
from pyngrok import ngrok
import os

# Put your ngrok auth token here (the long string you had earlier)
os.environ['NGROK_AUTH_TOKEN'] = '34mP4pTTHmzflKgiWPHNI3LANG4_2mJdyENQ8JCPaPHpcfwwB'

def start_server(port=5000):
    # Set auth token
    ngrok_token = os.environ.get('NGROK_AUTH_TOKEN')
    ngrok.set_auth_token(ngrok_token)

    # Start ngrok tunnel
    public_url = ngrok.connect(port).public_url

    print("\n" + "="*60)
    print("🚀 Colab Backend Started!")
    print("="*60)
    print(f"\n🔗 COPY THIS PUBLIC URL: {public_url}")
    print("\n" + "="*60 + "\n")

    # Run Flask app
    app.run(host='0.0.0.0', port=port)

if __name__ == "__main__":
    start_server(port=5000)